import { Language, TierLevel, PricingTier, TranslateFn } from './types';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // ... existing translations ...
    appName: "SnapifY",
    appSubtitle: "Event Sharing Platform", // Added this
    heroTitlePrefix: "Relive the Magic,",
    heroTitleSuffix: "Forever Yours",
    heroDesc: "Create shared albums for birthdays, weddings, and parties in seconds. Let your guests capture the magic with AI-enhanced organization.",
    getStarted: "Get Started",
    adminDemo: "Admin Demo",
    signIn: "Sign In",
    signUp: "Sign Up",
    fullName: "Full Name",
    email: "Email Address",
    password: "Password",
    createAccount: "Create Account",
    continueGoogle: "Continue with Google",
    terms: "By continuing, you agree to our Terms & Conditions",
    pricingTitle: "Simple, Transparent Pricing",
    bestValue: "Best Value",
    forProfessionals: "For Professionals",
    event: "event",
    currentPlan: "Current Plan",
    contactSales: "Contact Sales",
    startFree: "Start for Free",
    myEvents: "My Events",
    manageEvents: "Manage your parties and albums",
    newEvent: "New Event",
    noEvents: "No events yet",
    createFirst: "Create your first event to start snapping memories with friends!",
    createNow: "Create an event now",
    dateTBD: "Date TBD",
    memories: "memories",
    owner: "Owner",
    expired: "Expired",
    active: "Active",
    forever: "Forever",
    copyLink: "Copy Link",
    hostedBy: "Hosted by",
    gallery: "Gallery",
    noPhotos: "No photos yet",
    beFirst: "Be the first to snap a moment!",
    snap: "Snap",
    upload: "Upload",
    joinParty: "Join the Party",
    enterName: "Enter your name to contribute photos",
    yourName: "Your Name",
    continue: "Continue",
    cancel: "Cancel",
    createEvent: "Create New Event",
    eventTitle: "Event Title",
    eventTheme: "Event Theme",
    eventDate: "Event Date",
    setDate: "Set Date",
    aiDesc: "AI Description",
    autoGenerate: "Auto-Generate",
    generating: "Generating...",
    aiPlaceholder: "Click auto-generate to let AI write a fun description...",
    createParty: "Create Party",
    guest: "Guest",
    logOut: "Log Out",
    home: "Home",
    adminDashboard: "SnapifY Admin",
    masterControl: "Master Control Dashboard",
    users: "Users",
    events: "Events",
    exit: "Exit",
    totalUsers: "Total Users",
    totalEvents: "Total Events",
    totalMedia: "Total Media",
    storage: "Storage",
    registeredUsers: "Registered Users",
    tier: "Tier",
    actions: "Actions",
    deleteUserConfirm: "Are you sure you want to delete this user and all their data?",
    storageUsage: "Storage Usage by User",
    systemEvents: "System Events",
    host: "Host",
    status: "Status",
    mediaCount: "Media Count",
    items: "items",
    noDate: "No Date",
    exp: "Exp",
    unlimited: "Unlimited",
    editEvent: "Edit Event",
    modifyExpiration: "Modify Expiration",
    neverExpires: "Never Expires",
    expireImmediately: "Expire Immediately",
    setNewDuration: "Set New Duration (from now)",
    saveChanges: "Save Changes",
    modifyExpirationNote: "Modifying expiration will reset the timer starting from the moment you click Save.",
    seconds: "Seconds",
    minutes: "Minutes",
    hours: "Hours",
    days: "Days",
    managing: "Managing",
    mediaItems: "media items",
    noMedia: "No media in this event",
    deleteEventConfirm: "Delete this event and all its media permanently?",
    cameraError: "Unable to access camera. Please check permissions.",
    takePhoto: "Take Photo",
    retry: "Retry",
    eventExpiredTitle: "Event Expired",
    eventExpiredMsg: "This event's access period has ended. The gallery is no longer accessible to the public. Contact the event organizer for more information.",
    goHome: "Go Home",
    adminModeExpired: "Admin Mode: Viewing Expired Event",
    unknownUser: "Unknown User",
    authErrorFill: "Please fill in all fields",
    authErrorEmail: "This email is already registered",
    authErrorInvalid: "Invalid credentials. Please try again.",
    linkCopied: "Link copied to clipboard!",
    salesContactMsg: "Thank you for your interest! Our sales team will contact you shortly to upgrade your plan.",
    adminSettings: "Admin Settings: Expiration",
    customDuration: "Custom Duration",
    iAmPhotographer: "I am a Photographer / Studio",
    studioName: "Studio / Business Name",
    studioDashboard: "Studio Dashboard",
    verifiedStudio: "Verified Studio",
    downloadAll: "Download All",
    views: "Views",
    watermark: "Apply Watermark",
    watermarkApplied: "Watermark will be applied",
    applyWatermark: "Apply Watermark",
    storageLimit: "Storage Limit Reached! Please upgrade to upload more.",
    videoRestricted: "Video uploads are available on Pro and Studio plans.",
    upgradeToUpload: "Upgrade to Upload",
    setCover: "Set as Cover",
    coverSet: "Cover image updated!",
    contactSalesTitle: "Contact Sales to Upgrade",
    contactSalesDesc: "To unlock this tier, please contact our sales team. An administrator will upgrade your account immediately.",
    openWhatsapp: "Open WhatsApp",
    openEmail: "Send Email",
    downloading: "Zipping...",
    downloadReady: "Download Ready",
    zipError: "Error creating zip file.",
    slideshow: "Slideshow",
    exitSlideshow: "Exit Slideshow",
    play: "Play",
    pause: "Pause",
    studioSettings: "Studio Settings",
    uploadLogo: "Upload Logo/Signature",
    logoDesc: "Upload a PNG with transparent background for best results. This will be applied to the bottom-right of all photos.",
    currentLogo: "Current Logo",
    removeLogo: "Remove Logo",
    saveSettings: "Save Settings",
    opacity: "Opacity",
    size: "Size",
    preview: "Watermark Preview",
    position: "Position",
    offsetX: "Horizontal Offset",
    offsetY: "Vertical Offset",
    topLeft: "Top Left",
    topRight: "Top Right",
    bottomLeft: "Bottom Left",
    bottomRight: "Bottom Right",
    center: "Center",
    guestbook: "Guestbook",
    leaveMessage: "Leave a message...",
    signGuestbook: "Sign Guestbook",
    noMessages: "No messages yet. Be the first!",
    messageSent: "Message sent!",
    pinRequired: "PIN Required",
    enterPin: "Enter Event PIN",
    submitPin: "Unlock Event",
    optionalPin: "Optional PIN Code",
    pinDesc: "Leave blank for public access",
    invalidPin: "Incorrect PIN",
    findMe: "Find Me",
    findMeTitle: "Find Me with AI",
    findMeDesc: "Upload a selfie and we'll highlight photos of you in this gallery.",
    uploadSelfie: "Take Selfie",
    scanning: "Scanning Gallery...",
    noFaceDetected: "No face detected in your selfie. Try again.",
    foundMatches: "Found Matches",
    noMatchesFound: "No photos of you found yet.",
    clearFilter: "Clear Filter",
    processing: "Processing Video...",
    switchCamera: "Switch Camera",
    backToApp: "Back to App",
    termsTitle: "Terms & Privacy Policy",
    effectiveDate: "Effective Date",
    introTitle: "Introduction",
    introText: "Welcome to SnapifY (\"Service\"). By accessing or using our Service, you agree to be bound by these Terms. This Service is a platform for creating shared event albums and capturing photos/videos.",
    gdprTitle: "GDPR Compliance & Data Privacy",
    gdprText: "We act as a Data Controller regarding your personal information. We are committed to protecting your privacy in accordance with the General Data Protection Regulation (GDPR).",
    dataCollectTitle: "Data We Collect",
    dataCollectList: "• Name & Email (for Authentication)\n• Uploaded Photos & Videos\n• Metadata (Date, Time of upload)\n• Device Fingerprint (for Security)",
    yourRightsTitle: "Your Rights",
    yourRightsList: "• Right to Access: View your data.\n• Right to Rectification: Correct details.\n• Right to Erasure: Request deletion.\n• Right to Portability: Download ZIPs.",
    gdprNote: "* Photos are stored based on the event host's plan. Expired events may be permanently deleted from our servers to ensure data minimization.",
    userRespTitle: "User Responsibilities",
    userRespText: "By using this Service, you agree NOT to:",
    userRespList: "• Upload content that is illegal, pornographic, violent, or offensive.\n• Infringe on the copyright or privacy rights of others.\n• Use the Service for any purpose that violates local laws.",
    userRespFooter: "We reserve the right to remove any content and suspend accounts that violate these terms without prior notice.",
    liabilityTitle: "Limitation of Liability",
    liabilityText1: "THE SERVICE IS PROVIDED \"AS IS\" AND \"AS AVAILABLE\" WITHOUT WARRANTIES OF ANY KIND.",
    liabilityText2: "TO THE FULLEST EXTENT PERMITTED BY LAW, THE OWNER, ADMINISTRATORS, AND DEVELOPERS OF THIS SERVICE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE.",
    contactUsTitle: "Contact Us",
    contactUsText: "For data deletion requests, privacy concerns, or legal inquiries, please contact the Data Protection Officer / Administrator at:",
    agreeFooter: "By using SnapifY, you agree to these terms.",
    iAgree: "I Understand & Agree",
    termsLink: "Terms & Privacy",
    loginForPrivacy: "Login for Privacy Control",
    privacyNote: "Register to enable Private Uploads and manage your history.",
    guestPublicNote: "Photos uploaded as a guest will be public.",
    private: "Private",
    public: "Public",
    loginRequired: "Login required for private uploads",
    uploadPrivacy: "Upload Privacy",
    myUploads: "My Uploads",
    allPhotos: "All Photos",
    deleteMediaConfirm: "Are you sure you want to delete this media? This cannot be undone.",
    liveWall: "Live Wall",
    shareLiveWall: "Share Live Wall",
    scanToView: "Scan to view this live wall",
    untitled: "Untitled",
    by: "by",
    close: "Close",
    findMeDevMode: "⚠️ Experimental Feature: This feature is currently in development.",
    // PWA Strings
    installApp: "Install App",
    installAppDesc: "Install SnapifY for a better experience.",
    // New UI Strings
    addMemory: "Add Memory",
    tapToUpload: "TAP TO UPLOAD",
    loginHost: "Already have an account? Sign In",
    // New Modal Strings
    chooseAccess: "How would you like to join?",
    guestAccess: "Guest Access",
    continueAsGuest: "Continue as Guest",
    quickUpload: "Quick Uploads",
    publicGallery: "Public Gallery",
    memberLogin: "Login / Sign Up",
    privateUploadsHistory: "Private uploads & event history",
  },
  mk: {
    // ... existing translations ...
    appSubtitle: "Платформа за споделување настани",
    loginHost: "Веќе имате профил? Најавете се",
    addMemory: "Додади спомен",
    tapToUpload: "ДОПРИ ЗА ПРИКАЧУВАЊЕ",
    appName: "SnapifY",
    heroTitlePrefix: "Забавувај се.",
    heroTitleSuffix: "Сликај веднаш.",
    heroDesc: "Креирајте заеднички албуми за родендени, свадби и забави за неколку секунди. Дозволете им на гостите да ја доловат магијата.",
    getStarted: "Започни",
    adminDemo: "Админ демо",
    signIn: "Најави се",
    signUp: "Регистрирај се",
    fullName: "Целосно име",
    email: "Е-пошта",
    password: "Лозинка",
    createAccount: "Креирај профил",
    continueGoogle: "Продолжи со Google",
    terms: "Со продолжување, се согласувате со нашите Услови",
    pricingTitle: "Едноставни цени",
    bestValue: "Најдобро",
    forProfessionals: "За професионалци",
    event: "настан",
    currentPlan: "Тековен план",
    contactSales: "Контакт",
    startFree: "Започни бесплатно",
    myEvents: "Мои настани",
    manageEvents: "Управувајте со вашите забави и албуми",
    newEvent: "Нов настан",
    noEvents: "Сè уште нема настани",
    createFirst: "Креирајте го првиот настан и сликајте спомени!",
    createNow: "Креирај настан",
    dateTBD: "Датум наскоро",
    memories: "спомени",
    owner: "Сопственик",
    expired: "Истечен",
    active: "Активен",
    forever: "Засекогаш",
    copyLink: "Копирај линк",
    hostedBy: "Организирано од",
    gallery: "Галерија",
    noPhotos: "Нема фотографии",
    beFirst: "Бидете први што ќе сликате!",
    snap: "Сликај",
    upload: "Прикачи",
    joinParty: "Придружи се",
    enterName: "Внесете го вашето име за да прикачите слики",
    yourName: "Вашето име",
    continue: "Продолжи",
    cancel: "Откажи",
    createEvent: "Креирај нов настан",
    eventTitle: "Наслов на настан",
    eventTheme: "Тема на настан",
    eventDate: "Датум на настан",
    setDate: "Постави датум",
    aiDesc: "AI Опис",
    autoGenerate: "Генерирај",
    generating: "Се генерира...",
    aiPlaceholder: "Кликни генерирај за AI да напише опис...",
    createParty: "Креирај забава",
    guest: "Гостин",
    logOut: "Одјави се",
    home: "Почетна",
    adminDashboard: "SnapifY Админ",
    masterControl: "Главен контролен панел",
    users: "Корисници",
    events: "Настани",
    exit: "Излез",
    totalUsers: "Вкупно корисници",
    totalEvents: "Вкупно настани",
    totalMedia: "Вкупно медиуми",
    storage: "Меморија",
    registeredUsers: "Регистрирани корисници",
    tier: "Ниво",
    actions: "Акции",
    deleteUserConfirm: "Дали сте сигурни дека сакате да го избришете корисникот?",
    storageUsage: "Искористеност на меморија",
    systemEvents: "Системски настани",
    host: "Домаќин",
    status: "Статус",
    mediaCount: "Број на медиуми",
    items: "ставки",
    noDate: "Без датум",
    exp: "Истекува",
    unlimited: "Неограничено",
    editEvent: "Уреди настан",
    modifyExpiration: "Промени истекување",
    neverExpires: "Никогаш не истекува",
    expireImmediately: "Истечи веднаш",
    setNewDuration: "Постави ново времетраење",
    saveChanges: "Зачувај промени",
    modifyExpirationNote: "Промената на истекување ќе го ресетира тајмерот од моментот на зачувување.",
    seconds: "Секунди",
    minutes: "Минути",
    hours: "Часови",
    days: "Денови",
    managing: "Управување",
    mediaItems: "медиумски ставки",
    noMedia: "Нема медиуми во овој настан",
    deleteEventConfirm: "Избриши го настанот трајно?",
    cameraError: "Нема пристап до камерата.",
    takePhoto: "Сликај",
    retry: "Повторно",
    eventExpiredTitle: "Настанот е истечен",
    eventExpiredMsg: "Пристапот до овој настан е завршен. Контактирајте го организаторот.",
    goHome: "Оди на почетна",
    adminModeExpired: "Админ режим: Преглед на истечен настан",
    unknownUser: "Непознат корисник",
    authErrorFill: "Ве молиме пополнете ги сите полиња",
    authErrorEmail: "Оваа е-пошта е веќе регистрирана",
    authErrorInvalid: "Невалидни податоци. Обидете се повторно.",
    linkCopied: "Линкот е копиран!",
    salesContactMsg: "Ви благодариме! Нашиот тим ќе ве контактира.",
    adminSettings: "Админ: Истекување",
    customDuration: "Прилагодено",
    iAmPhotographer: "Јас сум фотограф / студио",
    studioName: "Име на студио / бизнис",
    studioDashboard: "Студио табла",
    verifiedStudio: "Верификувано студио",
    downloadAll: "Превземи се",
    views: "Прегледи",
    watermark: "Додади воден жиг",
    watermarkApplied: "Водениот жиг ќе биде применет",
    applyWatermark: "Примени воден жиг",
    storageLimit: "Достигнат лимит на меморија!",
    videoRestricted: "Видео прикачување е достапно за Pro и Studio.",
    upgradeToUpload: "Надградете за повеќе",
    setCover: "Постави како насловна",
    coverSet: "Насловната е ажурирана!",
    contactSalesTitle: "Контактирајте за надградба",
    contactSalesDesc: "За да го отклучите ова ниво, контактирајте не. Админ ќе го надгради вашиот профил.",
    openWhatsapp: "Отвори WhatsApp",
    openEmail: "Испрати е-пошта",
    downloading: "Се креира ZIP...",
    downloadReady: "Превземи",
    zipError: "Грешка при креирање ZIP",
    slideshow: "Слајдшоу",
    exitSlideshow: "Излези",
    play: "Пушти",
    pause: "Пауза",
    studioSettings: "Студио подесувања",
    uploadLogo: "Прикачи лого/потпис",
    logoDesc: "Прикачете PNG со транспарентна позадина. Ова ќе се примени на сите фотографии.",
    currentLogo: "Тековно лого",
    removeLogo: "Избриши лого",
    saveSettings: "Зачувај",
    opacity: "Проѕирност",
    size: "Големина",
    preview: "Преглед на жиг",
    position: "Позиција",
    offsetX: "Хоризонтално поместување",
    offsetY: "Вертикално поместување",
    topLeft: "Горе Лево",
    topRight: "Горе Десно",
    bottomLeft: "Долу Лево",
    bottomRight: "Долу Десно",
    center: "Центар",
    guestbook: "Книга на гости",
    leaveMessage: "Остави порака...",
    signGuestbook: "Потпиши се",
    noMessages: "Нема пораки. Биди прв!",
    messageSent: "Пораката е испратена!",
    pinRequired: "Потребен е PIN",
    enterPin: "Внесете PIN",
    submitPin: "Отклучи",
    optionalPin: "Опционален PIN код",
    pinDesc: "Оставете празно за јавен пристап",
    invalidPin: "Неточен PIN",
    findMe: "Најди ме",
    findMeTitle: "Најди ме со AI",
    findMeDesc: "Прикачете селфи и ние ќе ги означиме вашите слики.",
    uploadSelfie: "Сликај селфи",
    scanning: "Скенирање...",
    noFaceDetected: "Не е детектирано лице.",
    foundMatches: "Пронајдени совпаѓања",
    noMatchesFound: "Не се пронајдени фотографии.",
    clearFilter: "Исчисти филтер",
    processing: "Се процесира видео...",
    switchCamera: "Смени камера",
    backToApp: "Назад во апликацијата",
    termsTitle: "Услови и Приватност",
    effectiveDate: "Датум на стапување на сила",
    introTitle: "Вовед",
    introText: "Добредојдовте во SnapifY („Услуга“). Со пристап или користење на нашата Услуга, се согласувате да бидете обврзани со овие Услови. Оваа Услуга е платформа за креирање споделени албуми за настани и фотографирање/снимање.",
    gdprTitle: "GDPR Усогласеност и Приватност на податоци",
    gdprText: "Ние дејствуваме како Контролор на податоци во врска со вашите лични информации. Посветени сме на заштита на вашата приватност во согласност со Општата регулатива за заштита на податоци (GDPR).",
    dataCollectTitle: "Податоци што ги собираме",
    dataCollectList: "• Име и Е-пошта (за Автентикација)\n• Прикачени фотографии и видеа\n• Метаподатоци (Датум, Време на прикачување)\n• Отпечаток од уред (за Безбедност)",
    yourRightsTitle: "Вашите права",
    yourRightsList: "• Право на пристап: Преглед на вашите податоци.\n• Право на исправка: Поправка на детали.\n• Право на бришење: Барање за бришење.\n• Право на преносливост: Преземање ZIP.",
    gdprNote: "* Фотографиите се чуваат врз основа на планот на домаќинот на настанот. Истечените настани може трајно да се избришат од нашите сервери за да се обезбеди минимизирање на податоците.",
    userRespTitle: "Одговорности на корисникот",
    userRespText: "Со користење на оваа Услуга, се согласувате дека НЕМА:",
    userRespList: "• Да прикачувате содржина што е нелегална, порнографска, насилна или навредлива.\n• Да ги прекршувате авторските права или правата на приватност на другите.\n• Да ја користите Услугата за каква било цел што ги прекршува локалните закони.",
    userRespFooter: "Го задржуваме правото да отстраниме секаква содржина и да ги суспендираме сметките што ги прекршуваат овие услови без претходна најава.",
    liabilityTitle: "Ограничување на одговорноста",
    liabilityText1: "УСЛУГАТА СЕ ОБЕЗБЕДУВА „КАКО ШТО Е“ И „КАКО ШТО Е ДОСТАПНА“ БЕЗ НИКАКВИ ГАРАНЦИИ.",
    liabilityText2: "ДО НАЈГОЛЕМА МЕРА ДОЗВОЛЕНА СО ЗАКОН, СОПСТВЕНИКОТ, АДМИНИСТРАТОРИТЕ И РАЗВИВАЧИТЕ НА ОВАА УСЛУГА НЕ СЕ ОДГОВОРНИ ЗА БИЛО КАКВИ ИНДИРЕКТНИ, СЛУЧАЈНИ, ПОСЕБНИ, ПОСЛЕДИЧНИ ИЛИ КАЗНЕНИ ШТЕТИ, ИЛИ ЗА ГУБЕЊЕ НА ПОДАТОЦИ, КОРИСТЕЊЕ, ДОБРА ВОЛЈА ИЛИ ДРУГИ НЕМАТЕРИЈАЛНИ ЗАГУБИ, КОИ ПРОИЗЛЕГУВААТ ОД (А) ВАШИОТ ПРИСТАП ДО ИЛИ КОРИСТЕЊЕ ИЛИ НЕМОЖНОСТ ЗА ПРИСТАП ИЛИ КОРИСТЕЊЕ НА УСЛУГАТА; (Б) БИЛО КАКВО ОДНЕСУВАЊЕ ИЛИ СОДРЖИНА НА ТРЕТА СТРАНА НА УСЛУГАТА.",
    contactUsTitle: "Контакт",
    contactUsText: "За барања за бришење податоци, проблеми со приватноста или правни прашања, ве молиме контактирајте го Службеникот за заштита на податоци / Администраторот на:",
    agreeFooter: "Со користење на SnapifY, се согласувате со овие услови.",
    iAgree: "Разбирам и се согласувам",
    termsLink: "Услови и Приватност",
    loginForPrivacy: "Најави се за Приватност",
    privacyNote: "Регистрирај се за да користиш приватни прикачувања и историја.",
    guestPublicNote: "Сликите прикачени како гостин се јавни.",
    private: "Приватно",
    public: "Јавно",
    loginRequired: "Потребна е најава за приватност",
    uploadPrivacy: "Приватност на прикачување",
    myUploads: "Мои прикачувања",
    allPhotos: "Сите фотографии",
    deleteMediaConfirm: "Дали сте сигурни дека сакате да го избришете овој медиум?",
    liveWall: "Жив Зид",
    shareLiveWall: "Сподели Жив Зид",
    scanToView: "Скенирај за да го видиш овој жив зид",
    untitled: "Без наслов",
    by: "од",
    close: "Затвори",
    findMeDevMode: "⚠️ Експериментална функција: Оваа опција е моментално во развој.",
    // PWA Strings
    installApp: "Инсталирај Апликација",
    installAppDesc: "Инсталирај SnapifY за подобро искуство.",
    install: "Инсталирај",
    offlineMode: "Моментално сте офлајн",
    // New Modal Strings
    chooseAccess: "Како сакате да се приклучите?",
    guestAccess: "Гостински пристап",
    continueAsGuest: "Продолжи како гостин",
    quickUpload: "Брзо прикачување",
    publicGallery: "Јавна галерија",
    memberLogin: "Најава / Регистрација",
    privateUploadsHistory: "Приватни слики и историја",
  },
  tr: {
    // ... existing translations ...
    appSubtitle: "Etkinlik Paylaşım Platformu", // Added this
    appName: "SnapifY",
    heroTitlePrefix: "Partile.",
    heroTitleSuffix: "Anında Çek.",
    heroDesc: "Doğum günleri, düğünler ve partiler için saniyeler içinde paylaşılan albümler oluşturun. Misafirlerinizin büyüyü yakalamasına izin verin.",
    getStarted: "Başlayın",
    adminDemo: "Yönetici Demo",
    signIn: "Giriş Yap",
    signUp: "Kayıt Ol",
    fullName: "Ad Soyad",
    email: "E-posta Adresi",
    password: "Şifre",
    createAccount: "Hesap Oluştur",
    continueGoogle: "Google ile Devam Et",
    terms: "Devam ederek, Şartlar ve Koşulları kabul etmiş olursunuz",
    pricingTitle: "Basit, Şeffaf Fiyatlandırma",
    bestValue: "En İyi Değer",
    forProfessionals: "Profesyoneller İçin",
    event: "etkinlik",
    currentPlan: "Mevcut Plan",
    contactSales: "Satış ile İletişim",
    startFree: "Ücretsiz Başla",
    myEvents: "Etkinliklerim",
    manageEvents: "Partilerinizi ve albümlerinizi yönetin",
    newEvent: "Yeni Etkinlik",
    noEvents: "Henüz etkinlik yok",
    createFirst: "Arkadaşlarınızla anı yakalamak için ilk etkinliğinizi oluşturun!",
    createNow: "Şimdi etkinlik oluştur",
    dateTBD: "Tarih Belirlenecek",
    memories: "anılar",
    owner: "Sahip",
    expired: "Süresi Doldu",
    active: "Aktif",
    forever: "Sonsuza Dek",
    copyLink: "Bağlantıyı Kopyala",
    hostedBy: "Ev Sahibi",
    gallery: "Galeri",
    noPhotos: "Henüz fotoğraf yok",
    beFirst: "İlk fotoğrafı çeken siz olun!",
    snap: "Çek",
    upload: "Yükle",
    joinParty: "Partiye Katıl",
    enterName: "Fotoğraf yüklemek için adınızı girin",
    yourName: "Adınız",
    continue: "Devam Et",
    cancel: "İptal",
    createEvent: "Yeni Etkinlik Oluştur",
    eventTitle: "Etkinlik Başlığı",
    eventTheme: "Etkinlik Teması",
    eventDate: "Etkinlik Tarihi",
    setDate: "Tarih Ayarla",
    aiDesc: "AI Açıklaması",
    autoGenerate: "Otomatik Oluştur",
    generating: "Oluşturuluyor...",
    aiPlaceholder: "AI'ın eğlenceli bir açıklama yazması için tıklayın...",
    createParty: "Parti Oluştur",
    guest: "Misafir",
    logOut: "Çıkış Yap",
    home: "Ana Sayfa",
    adminDashboard: "SnapifY Yönetici",
    masterControl: "Ana Kontrol Paneli",
    users: "Kullanıcılar",
    events: "Etkinlikler",
    exit: "Çıkış",
    totalUsers: "Toplam Kullanıcı",
    totalEvents: "Toplam Etkinlik",
    totalMedia: "Toplam Medya",
    storage: "Depolama",
    registeredUsers: "Kayıtlı Kullanıcılar",
    tier: "Seviye",
    actions: "İşlemler",
    deleteUserConfirm: "Bu kullanıcıyı ve tüm verilerini silmek istediğinizden emin misiniz?",
    storageUsage: "Kullanıcı Depolama Kullanımı",
    systemEvents: "Sistem Etkinlikleri",
    host: "Ev Sahibi",
    status: "Durum",
    mediaCount: "Medya Sayısı",
    items: "öğe",
    noDate: "Tarih Yok",
    exp: "Bitiş",
    unlimited: "Sınırsız",
    editEvent: "Etkinliği Düzenle",
    modifyExpiration: "Süreyi Değiştir",
    neverExpires: "Asla Sona Ermez",
    expireImmediately: "Hemen Sona Erdir",
    setNewDuration: "Yeni Süre Belirle",
    saveChanges: "Değişiklikleri Kaydet",
    modifyExpirationNote: "Süreyi değiştirmek, kaydettiğiniz andan itibaren zamanlayıcıyı sıfırlar.",
    seconds: "Saniye",
    minutes: "Dakika",
    hours: "Saat",
    days: "Gün",
    managing: "Yönetiliyor",
    mediaItems: "medya öğesi",
    noMedia: "Bu etkinlikte medya yok",
    deleteEventConfirm: "Bu etkinliği kalıcı olarak sil?",
    cameraError: "Kameraya erişilemiyor. İzinleri kontrol edin.",
    takePhoto: "Fotoğraf Çek",
    retry: "Tekrar Dene",
    eventExpiredTitle: "Etkinlik Sona Erdi",
    eventExpiredMsg: "Bu etkinliğe erişim süresi doldu. Daha fazla bilgi için organizatörle iletişime geçin.",
    goHome: "Ana Sayfaya Git",
    adminModeExpired: "Yönetici Modu: Süresi Dolmuş Etkinlik",
    unknownUser: "Bilinmeyen Kullanıcı",
    authErrorFill: "Lütfen tüm alanları doldurun",
    authErrorEmail: "Bu e-posta zaten kayıtlı",
    authErrorInvalid: "Geçersiz bilgiler. Tekrar deneyin.",
    linkCopied: "Bağlantı panoya kopyalandı!",
    salesContactMsg: "İlginiz için teşekkürler! Satış ekibimiz sizinle iletişime geçecek.",
    adminSettings: "Yönetici Ayarları: Süre",
    customDuration: "Özel Süre",
    iAmPhotographer: "Ben Bir Fotoğrafçıyım / Stüdyoyum",
    studioName: "Stüdyo / İşletme Adı",
    studioDashboard: "Stüdyo Paneli",
    verifiedStudio: "Onaylı Stüdyo",
    downloadAll: "Tümünü İndir",
    views: "Görüntüleme",
    watermark: "Filigran Ekle",
    watermarkApplied: "Filigran uygulanacak",
    applyWatermark: "Filigran Uygula",
    storageLimit: "Depolama Sınırına Ulaşıldı!",
    videoRestricted: "Video yüklemeleri Pro ve Studio planlarında mevcuttur.",
    upgradeToUpload: "Yüklemek için Yükselt",
    setCover: "Kapak Olarak Ayarla",
    coverSet: "Kapak güncellendi!",
    contactSalesTitle: "Yükseltmek için İletişime Geçin",
    contactSalesDesc: "Bu seviyenin kilidini açmak için lütfen bizimle iletişime geçin. Bir yönetici hesabınızı yükseltecektir.",
    openWhatsapp: "WhatsApp'ı Aç",
    openEmail: "E-posta Gönder",
    downloading: "Sıkıştırılıyor...",
    downloadReady: "İndirme Hazır",
    zipError: "ZIP hatası",
    slideshow: "Slayt Gösterisi",
    exitSlideshow: "Çık",
    play: "Oynat",
    pause: "Duraklat",
    studioSettings: "Stüdyo Ayarları",
    uploadLogo: "Logo/İmza Yükle",
    logoDesc: "En iyi sonuç için şeffaf arka planlı PNG yükleyin. Tüm fotoğrafların sağ alt köşesine uygulanacaktır.",
    currentLogo: "Mevcut Logo",
    removeLogo: "Logoyu Kaldır",
    saveSettings: "Ayarları Kaydet",
    opacity: "Opaklık",
    size: "Boyut",
    preview: "Filigran Önizleme",
    position: "Pozisyon",
    offsetX: "Yatay Ofset",
    offsetY: "Dikey Ofset",
    topLeft: "Sol Üst",
    topRight: "Sağ Üst",
    bottomLeft: "Sol Alt",
    bottomRight: "Sağ Alt",
    center: "Orta",
    guestbook: "Ziyaretçi Defteri",
    leaveMessage: "Mesaj bırakın...",
    signGuestbook: "İmzala",
    noMessages: "Henüz mesaj yok. İlk siz olun!",
    messageSent: "Mesaj gönderildi!",
    pinRequired: "PIN Gerekli",
    enterPin: "Etkinlik PIN'ini Girin",
    submitPin: "Etkinliği Aç",
    optionalPin: "İsteğe Bağlı PIN Kodu",
    pinDesc: "Herkese açık erişim için boş bırakın",
    invalidPin: "Hatalı PIN",
    findMe: "Beni Bul",
    findMeTitle: "AI ile Beni Bul",
    findMeDesc: "Bir selfie yükleyin ve bu galerideki fotoğraflarınızı vurgulayalım.",
    uploadSelfie: "Selfie Çek",
    scanning: "Galeri Taranıyor...",
    noFaceDetected: "Yüz algılanamadı. Tekrar deneyin.",
    foundMatches: "Eşleşmeler Bulundu",
    noMatchesFound: "Henüz fotoğrafınız bulunamadı.",
    clearFilter: "Filtreyi Temizle",
    processing: "Video İşleniyor...",
    switchCamera: "Kamerayı Değiştir",
    backToApp: "Uygulamaya Dön",
    termsTitle: "Şartlar ve Gizlilik Politikası",
    effectiveDate: "Yürürlük Tarihi",
    introTitle: "Giriş",
    introText: "SnapifY'a (\"Hizmet\") hoş geldiniz. Hizmetimize erişerek veya kullanarak, bu Şartlara bağlı kalmayı kabul edersiniz. Bu Hizmet, paylaşılan etkinlik albümleri oluşturmak ve fotoğraf/video çekmek için bir platformdur.",
    gdprTitle: "GDPR Uyumluluğu ve Veri Gizliliği",
    gdprText: "Kişisel bilgilerinizle ilgili olarak Veri Sorumlusu olarak hareket ediyoruz. Gizliliğinizi Genel Veri Koruma Yönetmeliği (GDPR) uyarınca korumayı taahhüt ediyoruz.",
    dataCollectTitle: "Topladığımız Veriler",
    dataCollectList: "• Ad ve E-posta (Kimlik Doğrulama için)\n• Yüklenen Fotoğraflar ve Videolar\n• Meta Veriler (Yükleme Tarihi, Saati)\n• Cihaz Parmak İzi (Güvenlik için)",
    yourRightsTitle: "Haklarınız",
    yourRightsList: "• Erişim Hakkı: Verilerinizi görüntüleyin.\n• Düzeltme Hakkı: Ayrıntıları düzeltin.\n• Silme Hakkı: Silme talebinde bulunun.\n• Taşınabilirlik Hakkı: ZIP indirin.",
    gdprNote: "* Fotoğraflar, etkinlik sahibinin planına göre saklanır. Süresi dolan etkinlikler, veri minimizasyonunu sağlamak için sunucularımızdan kalıcı olarak silinebilir.",
    userRespTitle: "Kullanıcı Sorumlulukları",
    userRespText: "Bu Hizmeti kullanarak, aşağıdakileri YAPMAMAYI kabul edersiniz:",
    userRespList: "• Yasa dışı, pornografik, şiddet içeren veya saldırgan içerik yüklemek.\n• Başkalarının telif hakkı veya gizlilik haklarını ihlal etmek.\n• Hizmeti yerel yasaları ihlal eden herhangi bir amaç için kullanmak.",
    userRespFooter: "Bu şartları ihlal eden herhangi bir içeriği kaldırma ve hesapları önceden haber vermeksizin askıya alma hakkımızı saklı tutarız.",
    liabilityTitle: "Sorumluluk Sınırlaması",
    liabilityText1: "HİZMET \"OLDUĞU GİBİ\" VE \"MEVCUT OLDUĞU ŞEKİLDE\" HERHANGİ BİR GARANTİ OLMAKSIZIN SAĞLANIR.",
    liabilityText2: "YASALARIN İZİN VERDİĞİ EN GENİŞ ÖLÇÜDE, BU HİZMETİN SAHİBİ, YÖNETİCİLERİ VE GELİŞTİRİCİLERİ; (A) HİZMETE ERİŞİMİNİZ VEYA KULLANIMINIZ VEYA ERİŞEMEMENİZ VEYA KULLANAMAMANIZ; (B) HİZMETTEKİ HERHANGİ BİR ÜÇÜNCÜ TARAFIN HERHANGİ BİR DAVRANIŞI VEYA İÇERİĞİNDEN KAYNAKLANAN HERHANGİ BİR DOLAYLI, ARIZİ, ÖZEL, SONUÇ OLARAK ORTAYA ÇIKAN VEYA CEZAİ HASARLARDAN VEYA VERİ, KULLANIM, İYİ NİYET VEYA DİĞER MADDİ OLMAYAN KAYIPLARDAN SORUMLU OLMAYACAKTIR.",
    contactUsTitle: "Bize Ulaşın",
    contactUsText: "Veri silme talepleri, gizlilik endişeleri veya yasal sorular için lütfen Veri Koruma Görevlisi / Yönetici ile şu adresten iletişime geçin:",
    agreeFooter: "SnapifY'ı kullanarak, bu şartları kabul etmiş olursunuz.",
    iAgree: "Anlıyorum ve Kabul Ediyorum",
    termsLink: "Şartlar ve Gizlilik",
    loginForPrivacy: "Gizlilik Kontrolü için Giriş Yapın",
    privacyNote: "Özel Yüklemeleri etkinleştirmek ve geçmişinizi yönetmek için kaydolun.",
    guestPublicNote: "Misafir olarak yüklenen fotoğraflar herkese açık olacaktır.",
    private: "Özel",
    public: "Genel",
    loginRequired: "Özel yüklemeler için giriş gerekli",
    uploadPrivacy: "Yükleme Gizliliği",
    myUploads: "Yüklemelerim",
    allPhotos: "Tüm Fotoğraflar",
    deleteMediaConfirm: "Bu medyayı silmek istediğinizden emin misiniz?",
    liveWall: "Canlı Duvar",
    shareLiveWall: "Canlı Duvarı Paylaş",
    scanToView: "Bu canlı duvarı görmek için tarayın",
    untitled: "Başlıksız",
    by: "tarafından",
    close: "Kapat",
    // NEW
    findMeDevMode: "⚠️ Deneysel Özellik: Bu özellik şu anda geliştirme aşamasındadır.",
    installApp: "Uygulamayı Yükle",
    installAppDesc: "Daha iyi bir deneyim için SnapifY'ı yükleyin.",
    install: "Yükle",
    offlineMode: "Şu anda çevrimdışısınız",
    // New UI Strings
    addMemory: "Anı Ekle",
    tapToUpload: "YÜKLEMEK İÇİN DOKUN",
    loginHost: "Zaten hesabınız var mı? Giriş Yap",
    // New Modal Strings
    chooseAccess: "Nasıl katılmak istersiniz?",
    guestAccess: "Misafir Girişi",
    continueAsGuest: "Misafir Olarak Devam Et",
    quickUpload: "Hızlı Yükleme",
    publicGallery: "Herkese Açık Galeri",
    memberLogin: "Giriş Yap / Kayıt Ol",
    privateUploadsHistory: "Özel yüklemeler ve etkinlik geçmişi",
  },
  sq: {
    // ... existing translations ...
    appSubtitle: "Platformë për Ndarjen e Ngjarjeve", // Added this
    loginHost: "Keni llogari? Hyni",
    addMemory: "Shto Kujtime",
    tapToUpload: "PREK PËR TË NGARKUAR",
    appName: "SnapifY",
    heroTitlePrefix: "Festo Fort.",
    heroTitleSuffix: "Shkrep Tani.",
    heroDesc: "Krijoni albume të përbashkëta për ditëlindje, dasma dhe festa në sekonda. Lejoni mysafirët tuaj të kapin magjinë.",
    getStarted: "Fillo Tani",
    adminDemo: "Demo Admin",
    signIn: "Hyni",
    signUp: "Regjistrohu",
    fullName: "Emri i Plotë",
    email: "Adresa Email",
    password: "Fjalëkalimi",
    createAccount: "Krijo Llogari",
    continueGoogle: "Vazhdo me Google",
    terms: "Duke vazhduar, ju pajtoheni me Kushtet tona",
    pricingTitle: "Çmime të Thjeshta",
    bestValue: "Vlera më e mirë",
    forProfessionals: "Për Profesionistët",
    event: "ngjarje",
    currentPlan: "Plani Aktual",
    contactSales: "Kontakto Shitjet",
    startFree: "Fillo Falas",
    myEvents: "Ngjarjet e Mia",
    manageEvents: "Menaxho festat dhe albumet e tua",
    newEvent: "Ngjarje e Re",
    noEvents: "Ende asnjë ngjarje",
    createFirst: "Krijo ngjarjen tënde të parë!",
    createNow: "Krijo ngjarje tani",
    dateTBD: "Data së shpejti",
    memories: "kujtime",
    owner: "Pronari",
    expired: "Skaduar",
    active: "Aktive",
    forever: "Përgjithmonë",
    copyLink: "Kopjo Linkun",
    hostedBy: "Organizuar nga",
    gallery: "Galeria",
    noPhotos: "Asnjë foto ende",
    beFirst: "Bëhu i pari që shkrep një moment!",
    snap: "Shkrep",
    upload: "Ngarko",
    joinParty: "Bashkohu në Festë",
    enterName: "Shkruani emrin tuaj për të ngarkuar foto",
    yourName: "Emri Juaj",
    continue: "Vazhdo",
    cancel: "Anulo",
    createEvent: "Krijo Ngjarje të Re",
    eventTitle: "Titulli i Ngjarjes",
    eventTheme: "Tema e Ngjarjes",
    eventDate: "Data e Ngjarjes",
    setDate: "Cakto Datën",
    aiDesc: "Përshkrim AI",
    autoGenerate: "Gjenero",
    generating: "Po gjenerohet...",
    aiPlaceholder: "Kliko për të gjeneruar një përshkrim...",
    createParty: "Krijo Festë",
    guest: "Mysafir",
    logOut: "Dil",
    home: "Kreu",
    adminDashboard: "SnapifY Admin",
    masterControl: "Paneli Kryesor i Kontrollit",
    users: "Përdoruesit",
    events: "Ngjarjet",
    exit: "Dalja",
    totalUsers: "Gjithsej Përdorues",
    totalEvents: "Gjithsej Ngjarje",
    totalMedia: "Gjithsej Media",
    storage: "Hapësira",
    registeredUsers: "Përdoruesit e Regjistruar",
    tier: "Niveli",
    actions: "Veprime",
    deleteUserConfirm: "A jeni të sigurt që doni ta fshini këtë përdorues?",
    storageUsage: "Përdorimi i Hapësirës",
    systemEvents: "Ngjarjet e Sistemit",
    host: "Mikpritësi",
    status: "Statusi",
    mediaCount: "Numri i Mediave",
    items: "artikuj",
    noDate: "Pa Datë",
    exp: "Skadon",
    unlimited: "Pa limit",
    editEvent: "Ndrysho Ngjarjen",
    modifyExpiration: "Ndrysho Skadimin",
    neverExpires: "Nuk Skadon Kurrë",
    expireImmediately: "Skado Menjëherë",
    setNewDuration: "Cakto Kohëzgjatje të Re",
    saveChanges: "Ruaj Ndryshimet",
    modifyExpirationNote: "Ndryshimi i skadimit do të rifillojë kohëmatësin.",
    seconds: "Sekonda",
    minutes: "Minuta",
    hours: "Orë",
    days: "Ditë",
    managing: "Duke menaxhuar",
    mediaItems: "artikuj media",
    noMedia: "Asnjë media në këtë ngjarje",
    deleteEventConfirm: "Fshi këtë ngjarje përgjithmonë?",
    cameraError: "Nuk mund të qaset kamera.",
    takePhoto: "Bëj Foto",
    retry: "Provo Përsëri",
    eventExpiredTitle: "Ngjarja ka Skaduar",
    eventExpiredMsg: "Qasja në këtë ngjarje ka përfunduar.",
    goHome: "Shko në Kreu",
    adminModeExpired: "Admin: Po shikon ngjarje të skaduar",
    unknownUser: "Përdorues i Panjohur",
    authErrorFill: "Ju lutemi plotësoni të gjitha fushat",
    authErrorEmail: "Kjo email është regjistruar tashmë",
    authErrorInvalid: "Të dhëna të pasakta. Provo përsëri.",
    linkCopied: "Linku u kopjua!",
    salesContactMsg: "Faleminderit! Ekipi ynë do t'ju kontaktojë.",
    adminSettings: "Cilësimet Admin: Skadimi",
    customDuration: "Kohëzgjatje e Veçantë",
    iAmPhotographer: "Jam Fotograf / Studio",
    studioName: "Emri i Studios / Biznesit",
    studioDashboard: "Paneli i Studios",
    verifiedStudio: "Studio e Verifikuar",
    downloadAll: "Shkarko Të Gjitha",
    views: "Shikime",
    watermark: "Apliko Watermark",
    watermarkApplied: "Watermark do të aplikohet",
    applyWatermark: "Apliko Watermark",
    storageLimit: "Kufiri i Hapësirës u Arrit!",
    videoRestricted: "Videot janë vetëm për planet Pro dhe Studio.",
    upgradeToUpload: "Përmirëso për të Ngarkuar",
    setCover: "Cakto si Kopertinë",
    coverSet: "Kopertina u përditësua!",
    contactSalesTitle: "Kontaktoni Shitjet për Përmirësim",
    contactSalesDesc: "Për të zhbllokuar këtë nivel, kontaktoni. Një administrator do ta përmirësojë llogarinë tuaj.",
    openWhatsapp: "Hap WhatsApp",
    openEmail: "Dërgo Email",
    downloading: "Po krijon ZIP...",
    downloadReady: "Gati për Shkarkim",
    zipError: "Gabim në krijimin e ZIP",
    slideshow: "Slideshow",
    exitSlideshow: "Dil",
    play: "Luaj",
    pause: "Pusho",
    studioSettings: "Cilësimet e Studios",
    uploadLogo: "Ngarko Logo/Nënshkrim",
    logoDesc: "Ngarkoni një PNG me sfond transparent. Do të vendoset në cepin e djathtë poshtë.",
    currentLogo: "Logo Aktuale",
    removeLogo: "Fshi Logo",
    saveSettings: "Ruaj Cilësimet",
    opacity: "Opaciteti",
    size: "Madhësia",
    preview: "Pamje paraprake",
    position: "Pozicioni",
    offsetX: "Zhvendosje Horizontale",
    offsetY: "Zhvendosje Vertikale",
    topLeft: "Lart Majtas",
    topRight: "Lart Djathtas",
    bottomLeft: "Poshtë Majtas",
    bottomRight: "Poshtë Djathtas",
    center: "Qendër",
    guestbook: "Libri i Mysafirëve",
    leaveMessage: "Lini një mesazh...",
    signGuestbook: "Nënshkruaj",
    noMessages: "Asnjë mesazh ende. Bëhu i pari!",
    messageSent: "Mesazhi u dërgua!",
    pinRequired: "Kërkohet PIN",
    enterPin: "Shkruani PIN-in",
    submitPin: "Zhblloko",
    optionalPin: "Kodi PIN Opsional",
    pinDesc: "Lëreni bosh për qasje publike",
    invalidPin: "PIN i Gabuar",
    findMe: "Më Gjej",
    findMeTitle: "Më Gjej me AI",
    findMeDesc: "Ngarkoni një selfie dhe do të gjejmë fotot tuaja.",
    uploadSelfie: "Bëj Selfie",
    scanning: "Po skanon galerinë...",
    noFaceDetected: "Nuk u gjet fytyrë. Provo përsëri.",
    foundMatches: "U Gjetën",
    noMatchesFound: "Asnjë foto e juaja ende.",
    clearFilter: "Pastro",
    processing: "Duke procesuar videon...",
    switchCamera: "Ndrysho Kamerën",
    backToApp: "Kthehu në Aplikacion",
    termsTitle: "Kushtet dhe Privatësia",
    effectiveDate: "Data e Hyjes në Fuqi",
    introTitle: "Hyrje",
    introText: "Mirësevini në SnapifY (\"Shërbimi\"). Duke hyrë ose përdorur Shërbimin tonë, ju pajtoheni që të jeni të detyruar nga këto Kushte. Ky Shërbim është një platformë për krijimin e albumeve të përbashkëta të ngjarjeve dhe kapjen e fotove/videove.",
    gdprTitle: "Përputhshmëria me GDPR dhe Privatësia e të Dhënave",
    gdprText: "Ne veprojmë si Kontrollues të Dhënash në lidhje me informacionin tuaj personal. Ne jemi të përkushtuar të mbrojmë privatësinë tuaj në përputhje me Rregulloren e Përgjithshme për Mbrojtjen e të Dhënave (GDPR).",
    dataCollectTitle: "Të Dhënat që Mbledhim",
    dataCollectList: "• Emri dhe Email-i (për Autentifikim)\n• Fotot dhe Videot e Ngarkuara\n• Të dhënat meta (Data, Koha e ngarkimit)\n• Gjurmët e Pajisjes (për Siguri)",
    yourRightsTitle: "Të Drejtat Tuaja",
    yourRightsList: "• E drejta për qasje: Shikoni të dhënat tuaja.\n• E drejta për korrigjim: Korrigjoni detajet.\n• E drejta për fshirje: Kërkoni fshirjen.\n• E drejta për transportueshmëri: Shkarkoni ZIP.",
    gdprNote: "* Fotot ruhen bazuar në planin e organizatorit të ngjarjes. Ngjarjet e skaduara mund të fshihen përgjithmonë nga serverët tanë për të siguruar minimizimin e të dhënave.",
    userRespTitle: "Përgjegjësitë e Përdoruesit",
    userRespText: "Duke përdorur këtë Shërbim, ju pajtoheni të MOS:",
    userRespList: "• Ngarkoni përmbajtje që është e paligjshme, pornografike, e dhunshme ose ofenduese.\n• Shkelni të drejtat e autorit ose të drejtat e privatësisë së të tjerëve.\n• Përdorni Shërbimin për ndonjë qëllim që shkel ligjet vendore.",
    userRespFooter: "Ne rezervojmë të drejtën të heqim çdo përmbajtje dhe të pezullojmë llogaritë që shkelin këto kushte pa njoftim paraprak.",
    liabilityTitle: "Kufizimi i Përgjegjësisë",
    liabilityText1: "SHËRBIMI OFROHET \"SIÇ ËSHTË\" DHE \"SIÇ ËSHTË I DISPONUESHËM\" PA ASNJË LLOJ GARANCIE.",
    liabilityText2: "NË SHKALLËN MË TË PLOTË TË LEJUAR NGA LIGJI, PRONARI, ADMINISTRATORËT DHE ZHVILLUESIT E KËTIJ SHËRBIMI NUK DO TË JENË PËRGJEGJËS PËR ASNJË DËM TË TËRTHORTË, AKSIDENTAL, TË VEÇANTË, TË RËNDËSISHËM OSE NDËSHKUES, OSE NDONJË HUMBJE TË TË DHËNAVE, PËRDORIMIT, EMRIT TË MIRË OSE HUMBJE TË TJERA TË PAPREKSHME, QË RRJEDHIN NGA (A) QASJA JUAJ OSE PËRDORIMI OSE PAMUNDËSIA PËR TË HYRË OSE PËRDORUR SHËRBIMIN; (B) ÇDO SJELLJE OSE PËRMBAJTJE E NDONJË PALE TË TRETË NË SHËRBIM.",
    contactUsTitle: "Na Kontaktoni",
    contactUsText: "Për kërkesa për fshirjen e të dhënave, shqetësime për privatësinë ose pyetje ligjore, ju lutemi kontaktoni Zyrtarin për Mbrojtjen e të Dhënave / Administratorin në:",
    agreeFooter: "Duke përdorur SnapifY, ju pajtoheni me këto kushte.",
    iAgree: "Kuptoj dhe Pajtohem",
    termsLink: "Kushtet dhe Privatësia",
    loginForPrivacy: "Hyni për Kontrollin e Privatësisë",
    privacyNote: "Regjistrohuni për të aktivizuar Ngarkimet Private dhe për të menaxhuar historinë tuaj.",
    guestPublicNote: "Fotot e ngarkuara si mysafir do të jenë publike.",
    private: "Private",
    public: "Publike",
    loginRequired: "Kërkohet hyrja për ngarkime private",
    uploadPrivacy: "Privatësia e Ngarkimit",
    myUploads: "Ngarkimet e Mia",
    allPhotos: "Të Gjitha Fotot",
    deleteMediaConfirm: "A jeni i sigurt se doni të fshini këtë media?",
    liveWall: "Mur i Gjallë",
    shareLiveWall: "Ndaj Murin e Gjallë",
    scanToView: "Skano për të parë këtë mur të gjallë",
    untitled: "Pa Titull",
    by: "nga",
    close: "Mbyll",
    // NEW
    findMeDevMode: "⚠️ Veçori Eksperimentale: Kjo veçori është aktualisht në zhvillim.",
    installApp: "Instalo Aplikacionin",
    installAppDesc: "Instalo SnapifY për një përvojë më të mirë.",
    install: "Instalo",
    offlineMode: "Ju jeni aktualisht offline",
    // New Modal Strings
    chooseAccess: "Si dëshironi të bashkoheni?",
    guestAccess: "Qasje si Mysafir",
    continueAsGuest: "Vazhdo si Mysafir",
    quickUpload: "Ngarkime të Shpejta",
    publicGallery: "Galeri Publike",
    memberLogin: "Hyni / Regjistrohuni",
    privateUploadsHistory: "Ngarkime private & historia e ngjarjeve",
  }
};

export const getPricingTiers = (t: TranslateFn): PricingTier[] => [
  {
    id: TierLevel.FREE,
    name: 'Party Starter',
    price: 'Free',
    features: ['7 Hours Access Limit', '100MB Storage', 'Standard Support', 'Ad-supported'],
    cta: t('startFree'),
    limit: '7 Hours Active Time'
  },
  {
    id: TierLevel.BASIC,
    name: 'Celebration Plus',
    price: '$9.99',
    features: ['10GB Storage', '30 Days Active', 'HD Photo Uploads', 'AI Auto-Captioning'],
    cta: t('contactSales'),
    limit: '30 Days Access'
  },
  {
    id: TierLevel.PRO,
    name: 'Gala Elite',
    price: '$29.99',
    features: ['30GB Storage', '30 Days Active', '4K Video Support', 'Priority Support', 'Custom Branding'],
    cta: t('contactSales'),
    limit: '30 Days Access'
  },
  {
    id: TierLevel.STUDIO,
    name: 'Studio Enterprise',
    price: '$99',
    features: ['Unlimited Events', 'Auto Watermarking', 'Studio Branding', 'Client Analytics', 'Instant ZIP Download'],
    cta: t('contactSales'),
    limit: 'Professional Suite'
  }
];

export const EVENT_THEMES = [
  { id: 'Birthday', label: 'Birthday', emoji: '🎂' },
  { id: 'Wedding', label: 'Wedding', emoji: '💍' },
  { id: 'Party', label: 'Party', emoji: '🎉' },
  { id: 'Corporate', label: 'Corporate', emoji: '💼' },
  { id: 'Graduation', label: 'Graduation', emoji: '🎓' },
  { id: 'Baby Shower', label: 'Baby Shower', emoji: '👶' },
  { id: 'Anniversary', label: 'Anniversary', emoji: '💝' },
  { id: 'Holiday', label: 'Holiday', emoji: '🎄' },
  { id: 'Sports', label: 'Sports', emoji: '⚽' },
  { id: 'Concert', label: 'Concert', emoji: '🎵' }
];

// Hero images for landing page
export const HERO_IMAGES = [
  "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&q=80&w=1920", 
  "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&q=80&w=1920", 
  "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?auto=format&fit=crop&q=80&w=1920", 
  "https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&q=80&w=1920"
];
